### ISSUE TITLE
콜밴 DB 모델 명세

### ISSUE THREAD

**Issue by pAnswering** [BCSDLab/Callvan#11]
Timetable 레포에 callVanServer 브랜치에 모델 추가해뒀습니다.

보시고 모델에 추가로 필요한 것 코멘트 남겨주시고

명세는 요구사항 취합되면 그때 작성할게요

**Comment by pAnswering** [comment]
콜밴 방 내부에서 댓글남기는것처럼 Comment가 필요한가요

**Comment by EunBeeJo** [comment]
아뇨 Comment는 필요없어요!
